include: package:very_good_analysis/analysis_options.4.0.0.yaml

analyzer:
  exclude:
  - "**.g.dart"
  - "**.freezed.dart"
  - "**.pb.dart"
  - "**.pbenum.dart"
  - "**.pbjson.dart"
  - "**.pbgrpc.dart"
  - 

linter:
  rules:
    public_member_api_docs: false

