name: meetup_demo
description: A Very Good Sample Demo for gRPC & Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <3.10.1"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  build_config: ^1.0.0
  freezed_annotation: ^2.2.0
  go_router: ^7.0.2
  grpc: ^3.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  protobuf: ^2.1.0
  models: 
    path: ../packages/models

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets: 
    - assets/
