// meetup_demo_server
protoc --dart_out=grpc:meetup_demo_server/lib/protos/generated protos/pizza.proto 
// meetup_demo (client)
protoc --dart_out=grpc:meetup_demo/lib/protos/generated protos/pizza.proto 