name: meetup_demo_server
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  build_config: ^1.0.0
  freezed_annotation: ^2.2.0
  grpc: ^3.1.0
  json_annotation: ^4.8.1
  models: 
    path: ../packages/models
  protobuf: ^2.1.0

dev_dependencies:
  very_good_analysis: ^4.0.0
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0